apiVersion: v1
kind: Service
metadata:
  name: awesome-service
  namespace: awesome-namespace-prod
spec:
  selector:
    app: awesome-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
