apiVersion: v1
kind: Service
metadata:
  name: {{ include "awesome-project.fullname" . }}
  namespace: awesome-namespace
  labels:
    {{- include "awesome-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "awesome-project.selectorLabels" . | nindent 4 }}
